change_city_label <- function(cities_names)
{
	cities_names <- tolower(cities_names)
	cities_names <- tools::toTitleCase(cities_names)
	cities_names <- gsub("Aracaju", "Aracajú", cities_names, fixed = TRUE)
	cities_names <- gsub("Belem", "Belém", cities_names, fixed = TRUE)
	cities_names <- gsub("Brasilia", "Brasília", cities_names, fixed = TRUE)
	cities_names <- gsub("Cuiaba", "Cuiabá", cities_names, fixed = TRUE)
	cities_names <- gsub("Florianopolis", "Florianópolis", cities_names, fixed = TRUE)
	cities_names <- gsub("Goiania", "Goiânia", cities_names, fixed = TRUE)
	cities_names <- gsub("Joao Pessoa", "João Pessoa", cities_names, fixed = TRUE)
	cities_names <- gsub("Macapa", "Macapá", cities_names, fixed = TRUE)
	cities_names <- gsub("Maceio", "Maceió", cities_names, fixed = TRUE)
	cities_names <- gsub("Rio De Janeiro", "Rio de Janeiro", cities_names, fixed = TRUE)
	cities_names <- gsub("Sao Luis", "São Luís", cities_names, fixed = TRUE)
	cities_names <- gsub("Sao Paulo", "São Paulo", cities_names, fixed = TRUE)
	cities_names <- gsub("Vitoria", "Vitória", cities_names, fixed = TRUE)	
	return(cities_names)
}